// BrandColors.swift
// Healthy Pet Tracker — Apps for Hope
// Developed by Tara Knight | @Hopetheservicedoodle
//
// Canonical brand token reference for the Apps for Hope design system.
// See: Brand Palette Consolidation Plan.docx
//
// All shared tokens below are auto-generated by Xcode from Assets.xcassets
// via GeneratedAssetSymbols.swift. This file is the naming reference only.
//
// ─── Shared canonical tokens ─────────────────────────────────────────────────
//
//   Color.background         — #F5EFEA cream, primary app background
//   Color.surface            — near-white, card and modal surfaces
//   Color.fillSecondary      — warm beige, nav bar backgrounds and secondary fills
//   Color.textPrimary        — dark charcoal, all primary labels
//   Color.textSecondary      — medium gray, secondary labels and captions
//   Color.textTertiary       — #625A55 light gray, placeholders and hints (5.95:1)
//   Color.accentInteractive  — #386F3F dark sage, ALL interactive roles
//                              White text on this surface: 5.98:1 (WCAG AA)
//                              On cream background: 5.27:1 (WCAG AA)
//                              Never substitute accentLight or accentActive here
//   Color.accentLight        — light sage, decorative fills ONLY (never text/icon fg)
//   Color.success            — confirmation and completion states
//   Color.warning            — caution states (use as bg fill with textPrimary on top)
//   Color.error              — destructive and error states
//
// ─── HPT-specific tokens (not part of shared canonical set) ──────────────────
//
//   Color.accentActive       — mid sage, breed insights weight-range fill only
//   Color.borderSubtle       — subtle dividers and card strokes
//   Color.borderEmphasis     — emphasis borders

// No declarations needed here — Xcode auto-generates Color extensions for all
// asset catalog entries in GeneratedAssetSymbols.swift when you build.
