import SwiftUI
import UIKit

extension Color {
    // MARK: - Helper (kept for any ad-hoc hex use outside the palette)
    // Note: Color asset catalog colors (background, textPrimary, accentInteractive, etc.)
    // are auto-generated by Xcode in GeneratedAssetSymbols.swift — see BrandColors.swift
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let r = Double((int >> 16) & 0xFF) / 255
        let g = Double((int >> 8) & 0xFF) / 255
        let b = Double(int & 0xFF) / 255
        self.init(.sRGB, red: r, green: g, blue: b, opacity: 1)
    }
}

// MARK: - UIColor helpers
extension UIColor {

    /// Reads a named color from the asset catalog, which automatically
    /// provides the correct light / dark / high-contrast variant at runtime.
    static func named(_ name: String) -> UIColor {
        UIColor(named: name) ?? .label
    }

    /// Creates a UIColor from a 6-character hex string.
    /// Retained for use in configureNavigationBarAppearance and any
    /// one-off colours not in the palette.
    convenience init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let r = CGFloat((int >> 16) & 0xFF) / 255
        let g = CGFloat((int >> 8) & 0xFF) / 255
        let b = CGFloat(int & 0xFF) / 255
        self.init(red: r, green: g, blue: b, alpha: 1)
    }
}
